"""初期シードデータ定義 — ServiceFeature マスターデータ"""

SERVICE_FEATURES = [
    # service-001: テナント管理サービス (2件)
    {
        "id": "feature-service-001-01",
        "type": "service_feature",
        "service_id": "service-001",
        "feature_key": "audit_log",
        "feature_name": "監査ログ",
        "description": "テナント操作の監査ログを記録・保存する機能",
        "default_enabled": True,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-001",
    },
    {
        "id": "feature-service-001-02",
        "type": "service_feature",
        "service_id": "service-001",
        "feature_key": "auto_backup",
        "feature_name": "自動バックアップ",
        "description": "テナントデータを定期的に自動バックアップする機能",
        "default_enabled": False,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-001",
    },
    # service-002: 認証認可サービス (3件)
    {
        "id": "feature-service-002-01",
        "type": "service_feature",
        "service_id": "service-002",
        "feature_key": "mfa",
        "feature_name": "多要素認証 (MFA)",
        "description": "ログイン時にMFAを要求する機能",
        "default_enabled": False,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-002",
    },
    {
        "id": "feature-service-002-02",
        "type": "service_feature",
        "service_id": "service-002",
        "feature_key": "password_policy",
        "feature_name": "強化パスワードポリシー",
        "description": "強化されたパスワードポリシーを適用する機能",
        "default_enabled": True,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-002",
    },
    {
        "id": "feature-service-002-03",
        "type": "service_feature",
        "service_id": "service-002",
        "feature_key": "session_audit",
        "feature_name": "セッション監査",
        "description": "ユーザーセッションの監査ログを記録する機能",
        "default_enabled": False,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-002",
    },
    # service-003: 利用サービス設定サービス (2件)
    {
        "id": "feature-service-003-01",
        "type": "service_feature",
        "service_id": "service-003",
        "feature_key": "service_report",
        "feature_name": "サービス利用レポート",
        "description": "サービス利用状況のレポートを生成する機能",
        "default_enabled": True,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-003",
    },
    {
        "id": "feature-service-003-02",
        "type": "service_feature",
        "service_id": "service-003",
        "feature_key": "auto_provisioning",
        "feature_name": "自動プロビジョニング",
        "description": "テナント追加時に自動プロビジョニングを行う機能",
        "default_enabled": False,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-003",
    },
    # service-004: ファイル管理サービス (3件)
    {
        "id": "feature-service-004-01",
        "type": "service_feature",
        "service_id": "service-004",
        "feature_key": "version_control",
        "feature_name": "バージョン管理",
        "description": "ファイルのバージョン管理を行う機能",
        "default_enabled": True,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-004",
    },
    {
        "id": "feature-service-004-02",
        "type": "service_feature",
        "service_id": "service-004",
        "feature_key": "file_sharing",
        "feature_name": "ファイル外部共有",
        "description": "組織外へのファイル共有リンクを生成・管理する機能",
        "default_enabled": False,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-004",
    },
    {
        "id": "feature-service-004-03",
        "type": "service_feature",
        "service_id": "service-004",
        "feature_key": "auto_backup",
        "feature_name": "自動バックアップ",
        "description": "ファイルを定期的に自動バックアップする機能",
        "default_enabled": True,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-004",
    },
    # service-005: メッセージングサービス (3件)
    {
        "id": "feature-service-005-01",
        "type": "service_feature",
        "service_id": "service-005",
        "feature_key": "email_notification",
        "feature_name": "メール通知",
        "description": "メール通知を送信する機能",
        "default_enabled": True,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-005",
    },
    {
        "id": "feature-service-005-02",
        "type": "service_feature",
        "service_id": "service-005",
        "feature_key": "sms_notification",
        "feature_name": "SMS通知",
        "description": "SMS通知を送信する機能",
        "default_enabled": False,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-005",
    },
    {
        "id": "feature-service-005-03",
        "type": "service_feature",
        "service_id": "service-005",
        "feature_key": "push_notification",
        "feature_name": "プッシュ通知",
        "description": "プッシュ通知を送信する機能",
        "default_enabled": False,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-005",
    },
    # service-006: API利用サービス (3件)
    {
        "id": "feature-service-006-01",
        "type": "service_feature",
        "service_id": "service-006",
        "feature_key": "usage_analytics",
        "feature_name": "利用分析エクスポート",
        "description": "API利用分析データをエクスポートする機能",
        "default_enabled": True,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-006",
    },
    {
        "id": "feature-service-006-02",
        "type": "service_feature",
        "service_id": "service-006",
        "feature_key": "rate_limiting",
        "feature_name": "レートリミット設定",
        "description": "APIリクエストのレートリミットを設定する機能",
        "default_enabled": True,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-006",
    },
    {
        "id": "feature-service-006-03",
        "type": "service_feature",
        "service_id": "service-006",
        "feature_key": "api_audit_log",
        "feature_name": "API監査ログ",
        "description": "API利用の監査ログを記録する機能",
        "default_enabled": False,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-006",
    },
    # service-007: バックアップサービス (3件)
    {
        "id": "feature-service-007-01",
        "type": "service_feature",
        "service_id": "service-007",
        "feature_key": "incremental_backup",
        "feature_name": "増分バックアップ",
        "description": "増分バックアップを実行する機能",
        "default_enabled": True,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-007",
    },
    {
        "id": "feature-service-007-02",
        "type": "service_feature",
        "service_id": "service-007",
        "feature_key": "cross_region_backup",
        "feature_name": "クロスリージョンバックアップ",
        "description": "クロスリージョンへのバックアップを実行する機能",
        "default_enabled": False,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-007",
    },
    {
        "id": "feature-service-007-03",
        "type": "service_feature",
        "service_id": "service-007",
        "feature_key": "auto_schedule",
        "feature_name": "自動スケジュール",
        "description": "バックアップのスケジュールを自動管理する機能",
        "default_enabled": True,
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
        "partitionKey": "service-007",
    },
]
