"""デモンストレーション用サンプルデータ定義 — TenantServiceFeature"""

# テナント別機能設定サンプルデータ
# 各サンプルテナントの割り当てサービスに対するカスタム設定（2〜3件/テナント）
SAMPLE_TENANT_SERVICE_FEATURES = [
    # tenant-sample-001: file_sharing を有効化（デフォルト: False → True）
    {
        "id": "tenant-sample-001_feature-service-004-02",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-001",
        "service_id": "service-004",
        "feature_id": "feature-service-004-02",
        "feature_key": "file_sharing",
        "is_enabled": True,
        "updated_at": "2026-01-15T09:00:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-001",
    },
    # tenant-sample-001: sms_notification を有効化（デフォルト: False → True）
    {
        "id": "tenant-sample-001_feature-service-005-02",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-001",
        "service_id": "service-005",
        "feature_id": "feature-service-005-02",
        "feature_key": "sms_notification",
        "is_enabled": True,
        "updated_at": "2026-01-20T10:00:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-001",
    },
    # tenant-sample-001: cross_region_backup を有効化（デフォルト: False → True）
    {
        "id": "tenant-sample-001_feature-service-007-02",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-001",
        "service_id": "service-007",
        "feature_id": "feature-service-007-02",
        "feature_key": "cross_region_backup",
        "is_enabled": True,
        "updated_at": "2026-01-25T11:00:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-001",
    },
    # tenant-sample-002: file_sharing を無効化（デフォルト: False のまま明示的に設定）
    {
        "id": "tenant-sample-002_feature-service-004-02",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-002",
        "service_id": "service-004",
        "feature_id": "feature-service-004-02",
        "feature_key": "file_sharing",
        "is_enabled": False,
        "updated_at": "2026-01-18T14:00:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-002",
    },
    # tenant-sample-002: push_notification を有効化（デフォルト: False → True）
    {
        "id": "tenant-sample-002_feature-service-005-03",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-002",
        "service_id": "service-005",
        "feature_id": "feature-service-005-03",
        "feature_key": "push_notification",
        "is_enabled": True,
        "updated_at": "2026-01-22T08:30:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-002",
    },
    # tenant-sample-003: api_audit_log を有効化（デフォルト: False → True）
    {
        "id": "tenant-sample-003_feature-service-006-03",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-003",
        "service_id": "service-006",
        "feature_id": "feature-service-006-03",
        "feature_key": "api_audit_log",
        "is_enabled": True,
        "updated_at": "2026-02-01T10:00:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-003",
    },
    # tenant-sample-003: rate_limiting を無効化（デフォルト: True → False）
    {
        "id": "tenant-sample-003_feature-service-006-02",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-003",
        "service_id": "service-006",
        "feature_id": "feature-service-006-02",
        "feature_key": "rate_limiting",
        "is_enabled": False,
        "updated_at": "2026-02-05T13:00:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-003",
    },
    # tenant-sample-004: file_sharing を有効化（デフォルト: False → True）
    {
        "id": "tenant-sample-004_feature-service-004-02",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-004",
        "service_id": "service-004",
        "feature_id": "feature-service-004-02",
        "feature_key": "file_sharing",
        "is_enabled": True,
        "updated_at": "2026-02-10T09:00:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-004",
    },
    # tenant-sample-004: sms_notification を有効化（デフォルト: False → True）
    {
        "id": "tenant-sample-004_feature-service-005-02",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-004",
        "service_id": "service-005",
        "feature_id": "feature-service-005-02",
        "feature_key": "sms_notification",
        "is_enabled": True,
        "updated_at": "2026-02-12T10:30:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-004",
    },
    # tenant-sample-005: cross_region_backup を有効化（デフォルト: False → True）
    {
        "id": "tenant-sample-005_feature-service-007-02",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-005",
        "service_id": "service-007",
        "feature_id": "feature-service-007-02",
        "feature_key": "cross_region_backup",
        "is_enabled": True,
        "updated_at": "2026-02-15T11:00:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-005",
    },
    # tenant-sample-005: push_notification を有効化（デフォルト: False → True）
    {
        "id": "tenant-sample-005_feature-service-005-03",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-005",
        "service_id": "service-005",
        "feature_id": "feature-service-005-03",
        "feature_key": "push_notification",
        "is_enabled": True,
        "updated_at": "2026-02-16T14:00:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-005",
    },
]
